# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ToolChoice
ToolChoice

    ToolChoice(; value=nothing)
"""
mutable struct ToolChoice <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ String, ToolChoiceAnyOf }
    ToolChoice() = new()
    ToolChoice(value) = new(value)
end # type ToolChoice

function OpenAPI.property_type(::Type{ ToolChoice }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ToolChoice, name)
end
