# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ToolChoice_anyOf

    ToolChoiceAnyOf(;
        type=nothing,
        var"function"=nothing,
    )

    - type::String
    - var"function"::ToolChoiceAnyOfFunction
"""
Base.@kwdef mutable struct ToolChoiceAnyOf <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    var"function" = nothing # spec type: Union{ Nothing, ToolChoiceAnyOfFunction }

    function ToolChoiceAnyOf(type, var"function", )
        o = new(type, var"function", )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ToolChoiceAnyOf

const _property_types_ToolChoiceAnyOf = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("function")=>"ToolChoiceAnyOfFunction", )
OpenAPI.property_type(::Type{ ToolChoiceAnyOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ToolChoiceAnyOf[name]))}

function OpenAPI.check_required(o::ToolChoiceAnyOf)
    true
end

function OpenAPI.validate_properties(o::ToolChoiceAnyOf)
    OpenAPI.validate_property(ToolChoiceAnyOf, Symbol("type"), o.type)
    OpenAPI.validate_property(ToolChoiceAnyOf, Symbol("function"), o.var"function")
end

function OpenAPI.validate_property(::Type{ ToolChoiceAnyOf }, name::Symbol, val)

    if name === Symbol("type")
        OpenAPI.validate_param(name, "ToolChoiceAnyOf", :enum, val, ["function"])
    end


end
