# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Part_image_url

    PartImageUrl(;
        url=nothing,
    )

    - url::String
"""
Base.@kwdef mutable struct PartImageUrl <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing

    function PartImageUrl(url, )
        o = new(url, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PartImageUrl

const _property_types_PartImageUrl = Dict{Symbol,String}(Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ PartImageUrl }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PartImageUrl[name]))}

function OpenAPI.check_required(o::PartImageUrl)
    o.url === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PartImageUrl)
    OpenAPI.validate_property(PartImageUrl, Symbol("url"), o.url)
end

function OpenAPI.validate_property(::Type{ PartImageUrl }, name::Symbol, val)

end
