# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""textCompletion_request

    TextCompletionRequest(;
        model=nothing,
        prompt=nothing,
    )

    - model::String
    - prompt::String
"""
Base.@kwdef mutable struct TextCompletionRequest <: OpenAPI.APIModel
    model::Union{Nothing, String} = nothing
    prompt::Union{Nothing, String} = nothing

    function TextCompletionRequest(model, prompt, )
        o = new(model, prompt, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TextCompletionRequest

const _property_types_TextCompletionRequest = Dict{Symbol,String}(Symbol("model")=>"String", Symbol("prompt")=>"String", )
OpenAPI.property_type(::Type{ TextCompletionRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TextCompletionRequest[name]))}

function OpenAPI.check_required(o::TextCompletionRequest)
    o.model === nothing && (return false)
    o.prompt === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TextCompletionRequest)
    OpenAPI.validate_property(TextCompletionRequest, Symbol("model"), o.model)
    OpenAPI.validate_property(TextCompletionRequest, Symbol("prompt"), o.prompt)
end

function OpenAPI.validate_property(::Type{ TextCompletionRequest }, name::Symbol, val)


end
