# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""chatCompletions_request

    ChatCompletionsRequest(;
        model=nothing,
        messages=nothing,
        tools=nothing,
        tool_choice=nothing,
        response_format=nothing,
    )

    - model::String
    - messages::Vector{Message}
    - tools::Vector{Tool}
    - tool_choice::ToolChoice
    - response_format::ResponseFormat
"""
Base.@kwdef mutable struct ChatCompletionsRequest <: OpenAPI.APIModel
    model::Union{Nothing, String} = nothing
    messages::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Message} }
    tools::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Tool} }
    tool_choice = nothing # spec type: Union{ Nothing, ToolChoice }
    response_format = nothing # spec type: Union{ Nothing, ResponseFormat }

    function ChatCompletionsRequest(model, messages, tools, tool_choice, response_format, )
        o = new(model, messages, tools, tool_choice, response_format, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ChatCompletionsRequest

const _property_types_ChatCompletionsRequest = Dict{Symbol,String}(Symbol("model")=>"String", Symbol("messages")=>"Vector{Message}", Symbol("tools")=>"Vector{Tool}", Symbol("tool_choice")=>"ToolChoice", Symbol("response_format")=>"ResponseFormat", )
OpenAPI.property_type(::Type{ ChatCompletionsRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChatCompletionsRequest[name]))}

function OpenAPI.check_required(o::ChatCompletionsRequest)
    true
end

function OpenAPI.validate_properties(o::ChatCompletionsRequest)
    OpenAPI.validate_property(ChatCompletionsRequest, Symbol("model"), o.model)
    OpenAPI.validate_property(ChatCompletionsRequest, Symbol("messages"), o.messages)
    OpenAPI.validate_property(ChatCompletionsRequest, Symbol("tools"), o.tools)
    OpenAPI.validate_property(ChatCompletionsRequest, Symbol("tool_choice"), o.tool_choice)
    OpenAPI.validate_property(ChatCompletionsRequest, Symbol("response_format"), o.response_format)
end

function OpenAPI.validate_property(::Type{ ChatCompletionsRequest }, name::Symbol, val)





end
