# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ToolChoice_anyOf_function

    ToolChoiceAnyOfFunction(;
        name=nothing,
    )

    - name::String
"""
Base.@kwdef mutable struct ToolChoiceAnyOfFunction <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing

    function ToolChoiceAnyOfFunction(name, )
        o = new(name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ToolChoiceAnyOfFunction

const _property_types_ToolChoiceAnyOfFunction = Dict{Symbol,String}(Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ ToolChoiceAnyOfFunction }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ToolChoiceAnyOfFunction[name]))}

function OpenAPI.check_required(o::ToolChoiceAnyOfFunction)
    true
end

function OpenAPI.validate_properties(o::ToolChoiceAnyOfFunction)
    OpenAPI.validate_property(ToolChoiceAnyOfFunction, Symbol("name"), o.name)
end

function OpenAPI.validate_property(::Type{ ToolChoiceAnyOfFunction }, name::Symbol, val)

end
