# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "0.2.0"

include("modelincludes.jl")

include("apis/api_DefaultApi.jl")

# export models
export ChatCompletionsRequest
export FunctionDescription
export Message
export MessageContent
export Part
export PartFile
export PartImageUrl
export ResponseFormat
export ResponseFormatJsonSchema
export TextCompletionRequest
export Tool
export ToolChoice
export ToolChoiceAnyOf
export ToolChoiceAnyOfFunction

# export operations
export DefaultApi

end # module APIClient
