# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

include("models/model_ChatCompletionsRequest.jl")
include("models/model_FunctionDescription.jl")
include("models/model_Message.jl")
include("models/model_MessageContent.jl")
include("models/model_Part.jl")
include("models/model_PartFile.jl")
include("models/model_PartImageUrl.jl")
include("models/model_ResponseFormat.jl")
include("models/model_ResponseFormatJsonSchema.jl")
include("models/model_TextCompletionRequest.jl")
include("models/model_Tool.jl")
include("models/model_ToolChoice.jl")
include("models/model_ToolChoiceAnyOf.jl")
include("models/model_ToolChoiceAnyOfFunction.jl")
